//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furion.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furion.Validation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid age format. 的本地化字符串。
        /// </summary>
        internal static string AgeValidator_Invalid {
            get {
                return ResourceManager.GetString("AgeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid bank card number. 的本地化字符串。
        /// </summary>
        internal static string BankCardNumberValidator_Invalid {
            get {
                return ResourceManager.GetString("BankCardNumberValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Chinese name. 的本地化字符串。
        /// </summary>
        internal static string ChineseNameValidator_Invalid {
            get {
                return ResourceManager.GetString("ChineseNameValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Chinese. 的本地化字符串。
        /// </summary>
        internal static string ChineseValidator_Invalid {
            get {
                return ResourceManager.GetString("ChineseValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid color value. 的本地化字符串。
        /// </summary>
        internal static string ColorValueValidator_Invalid {
            get {
                return ResourceManager.GetString("ColorValueValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string CompositeValidator_Invalid {
            get {
                return ResourceManager.GetString("CompositeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string CustomValidator_Invalid {
            get {
                return ResourceManager.GetString("CustomValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid domain format. 的本地化字符串。
        /// </summary>
        internal static string DomainValidator_Invalid {
            get {
                return ResourceManager.GetString("DomainValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not end with the string {1}. 的本地化字符串。
        /// </summary>
        internal static string EndsWithValidator_Invalid {
            get {
                return ResourceManager.GetString("EndsWithValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string EqualValidator_Invalid {
            get {
                return ResourceManager.GetString("EqualValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be greater than or equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string GreaterThanOrEqualToValidator_Invalid {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be greater than {1}. 的本地化字符串。
        /// </summary>
        internal static string GreaterThanValidator_Invalid {
            get {
                return ResourceManager.GetString("GreaterThanValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Id card number format. 的本地化字符串。
        /// </summary>
        internal static string IdCardNumberValidator_invalid {
            get {
                return ResourceManager.GetString("IdCardNumberValidator_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be less than or equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string LessThanOrEqualToValidator_Invalid {
            get {
                return ResourceManager.GetString("LessThanOrEqualToValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be less than {1}. 的本地化字符串。
        /// </summary>
        internal static string LessThanValidator_Invalid {
            get {
                return ResourceManager.GetString("LessThanValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not allow empty values. 的本地化字符串。
        /// </summary>
        internal static string NotEmptyValidator_Invalid {
            get {
                return ResourceManager.GetString("NotEmptyValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} cannot be equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string NotEqualValidator_Invalid {
            get {
                return ResourceManager.GetString("NotEqualValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid password format. 的本地化字符串。
        /// </summary>
        internal static string PasswordValidator_Invalid {
            get {
                return ResourceManager.GetString("PasswordValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid phone number format. 的本地化字符串。
        /// </summary>
        internal static string PhoneNumberValidator_Invalid {
            get {
                return ResourceManager.GetString("PhoneNumberValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid postal code format. 的本地化字符串。
        /// </summary>
        internal static string PostalCodeValidator_Invalid {
            get {
                return ResourceManager.GetString("PostalCodeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} only allows for a single value. 的本地化字符串。
        /// </summary>
        internal static string SingleValidator_Invalid {
            get {
                return ResourceManager.GetString("SingleValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not start with the string {1}. 的本地化字符串。
        /// </summary>
        internal static string StartsWithValidator_Invalid {
            get {
                return ResourceManager.GetString("StartsWithValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not contain the string {1}. 的本地化字符串。
        /// </summary>
        internal static string StringContainsValidator_Invalid {
            get {
                return ResourceManager.GetString("StringContainsValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid strong password format. 的本地化字符串。
        /// </summary>
        internal static string StrongPasswordValidator_Invalid {
            get {
                return ResourceManager.GetString("StrongPasswordValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid telephone format. 的本地化字符串。
        /// </summary>
        internal static string TelephoneValidator_Invalid {
            get {
                return ResourceManager.GetString("TelephoneValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid username format. 的本地化字符串。
        /// </summary>
        internal static string UserNameValidator_Invalid {
            get {
                return ResourceManager.GetString("UserNameValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string ValidatorBase_Invalid {
            get {
                return ResourceManager.GetString("ValidatorBase_Invalid", resourceCulture);
            }
        }
    }
}
