//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furion.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Furion.Validation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid age format. 的本地化字符串。
        /// </summary>
        internal static string AgeValidator_Invalid {
            get {
                return ResourceManager.GetString("AgeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid bank card number. 的本地化字符串。
        /// </summary>
        internal static string BankCardNumberValidator_Invalid {
            get {
                return ResourceManager.GetString("BankCardNumberValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid base64 format. 的本地化字符串。
        /// </summary>
        internal static string Base64Validator_Invalid {
            get {
                return ResourceManager.GetString("Base64Validator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid value that can be converted to a boolean type. 的本地化字符串。
        /// </summary>
        internal static string BooleanValidator_Invalid {
            get {
                return ResourceManager.GetString("BooleanValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Chinese name. 的本地化字符串。
        /// </summary>
        internal static string ChineseNameValidator_Invalid {
            get {
                return ResourceManager.GetString("ChineseNameValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Chinese province. 的本地化字符串。
        /// </summary>
        internal static string ChineseProvinceValidator_Invalid {
            get {
                return ResourceManager.GetString("ChineseProvinceValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid Chinese. 的本地化字符串。
        /// </summary>
        internal static string ChineseValidator_Invalid {
            get {
                return ResourceManager.GetString("ChineseValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid color value. 的本地化字符串。
        /// </summary>
        internal static string ColorValueValidator_Invalid {
            get {
                return ResourceManager.GetString("ColorValueValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string CompositeValidator_Invalid {
            get {
                return ResourceManager.GetString("CompositeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid currency amount format. 的本地化字符串。
        /// </summary>
        internal static string CurrencyAmountValidator_Invalid {
            get {
                return ResourceManager.GetString("CurrencyAmountValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string CustomValidator_Invalid {
            get {
                return ResourceManager.GetString("CustomValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid date only format. 的本地化字符串。
        /// </summary>
        internal static string DateOnlyValidator_Invalid {
            get {
                return ResourceManager.GetString("DateOnlyValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid datetime format. 的本地化字符串。
        /// </summary>
        internal static string DateTimeValidator_Invalid {
            get {
                return ResourceManager.GetString("DateTimeValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid green plate number format. 的本地化字符串。
        /// </summary>
        internal static string GreenPlateNumberValidator_Invalid {
            get {
                return ResourceManager.GetString("GreenPlateNumberValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid number plate format. 的本地化字符串。
        /// </summary>
        internal static string NumberPlateValidator_Invalid {
            get {
                return ResourceManager.GetString("NumberPlateValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is required. 的本地化字符串。
        /// </summary>
        internal static string RequiredValidator_Invalid {
            get {
                return ResourceManager.GetString("RequiredValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid standard plate number format. 的本地化字符串。
        /// </summary>
        internal static string StandardPlateNumberValidator_Invalid {
            get {
                return ResourceManager.GetString("StandardPlateNumberValidator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid half day clock time format. 的本地化字符串。
        /// </summary>
        internal static string TimeOnly12Validator_Invalid {
            get {
                return ResourceManager.GetString("TimeOnly12Validator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is not a valid full day clock time format. 的本地化字符串。
        /// </summary>
        internal static string TimeOnly24Validator_Invalid {
            get {
                return ResourceManager.GetString("TimeOnly24Validator_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} is invalid. 的本地化字符串。
        /// </summary>
        internal static string ValidatorBase_Invalid {
            get {
                return ResourceManager.GetString("ValidatorBase_Invalid", resourceCulture);
            }
        }
    }
}
